import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/shared/lib/tanstack/providers";
import { Footer, Header, Toast } from "@/widgets";
import { Layout } from "@/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Layout>
            {children}
          </Layout>
          <Toast />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
